package orgmtheme

import (
	"fmt"
	"path/filepath"
	"strconv"
	"strings"
)

// Env contains filesystem roots used when planning rendered theme files.
type Env struct {
	ConfigHome string
	DataHome   string
}

// PlannedWrite is one rendered file path and its complete content.
type PlannedWrite struct {
	Path    string
	Content string
}

// BuildWrites renders active desktop theme files without writing them.
func BuildWrites(env Env, theme Theme) ([]PlannedWrite, error) {
	if env.ConfigHome == "" || !filepath.IsAbs(env.ConfigHome) {
		return nil, fmt.Errorf("ConfigHome must be an absolute path")
	}
	if env.DataHome == "" || !filepath.IsAbs(env.DataHome) {
		return nil, fmt.Errorf("DataHome must be an absolute path")
	}

	gtkSettings := renderGTKSettings(theme)
	gtkCSS := renderGTKCascade(theme)
	qt5Conf, qt5Colors := renderQT(theme, env.ConfigHome, "qt5ct")
	qt6Conf, qt6Colors := renderQT(theme, env.ConfigHome, "qt6ct")

	writes := []PlannedWrite{
		{Path: filepath.Join(env.ConfigHome, "kitty", "current-theme.conf"), Content: renderKitty(theme)},
		{Path: filepath.Join(env.ConfigHome, "rofi", "orgm-current.rasi"), Content: renderRofi(theme)},
		{Path: filepath.Join(env.ConfigHome, "fuzzel", "fuzzel.ini"), Content: renderFuzzel(theme)},
		{Path: filepath.Join(env.ConfigHome, "waybar", "orgm-current.css"), Content: renderWaybarPalette(theme)},
		{Path: filepath.Join(env.ConfigHome, "waybar-hypr", "orgm-current.css"), Content: renderWaybarHyprPalette(theme)},
		{Path: filepath.Join(env.ConfigHome, "conky", "orgm-colors.lua"), Content: renderConkyColors(theme)},
		{Path: filepath.Join(env.ConfigHome, "nwg-dock-hyprland", "orgm-current.css"), Content: renderDock()},
		{Path: filepath.Join(env.ConfigHome, "swaync", "orgm-current.css"), Content: renderSwayNC(theme)},
		{Path: filepath.Join(env.ConfigHome, "quickshell", "theme", "current.json"), Content: renderFixedQuickshell(theme)},
		{Path: filepath.Join(env.ConfigHome, "quickshell", "theme", "theme.json"), Content: renderFixedQuickshell(theme)},
		{Path: filepath.Join(env.ConfigHome, "gtk-3.0", "settings.ini"), Content: gtkSettings},
		{Path: filepath.Join(env.ConfigHome, "gtk-4.0", "settings.ini"), Content: gtkSettings},
		{Path: filepath.Join(env.ConfigHome, "gtk-4.0", "gtk.css"), Content: gtkCSS},
		{Path: filepath.Join(env.ConfigHome, "gtk-4.0", "gtk-dark.css"), Content: gtkCSS},
		{Path: filepath.Join(env.DataHome, "icons", "default", "index.theme"), Content: renderCursorIndex(theme)},
		{Path: filepath.Join(env.ConfigHome, "qt5ct", "qt5ct.conf"), Content: qt5Conf},
		{Path: filepath.Join(env.ConfigHome, "qt5ct", "colors", "orgm-current.colors"), Content: qt5Colors},
		{Path: filepath.Join(env.ConfigHome, "qt6ct", "qt6ct.conf"), Content: qt6Conf},
		{Path: filepath.Join(env.ConfigHome, "qt6ct", "colors", "orgm-current.colors"), Content: qt6Colors},
		{Path: filepath.Join(env.ConfigHome, "kdeglobals"), Content: renderKDEGlobals(theme)},
		{Path: filepath.Join(env.ConfigHome, "hypr", "scheme", "current.conf"), Content: renderHyprScheme(theme)},
		{Path: filepath.Join(env.ConfigHome, "vesktop", "settings", "quickcss.css"), Content: renderVesktop(theme)},
	}
	return writes, nil
}

func renderKitty(t Theme) string {
	opacity := t.KittyBackgroundOpacity
	if opacity == "" {
		opacity = "0.90"
	}
	return fmt.Sprintf(`# Generated by orgm-theme. Do not edit.
foreground #%s
background #%s
background_opacity %s
selection_foreground #%s
selection_background #%s
cursor #%s
cursor_text_color #%s
url_color #%s
active_border_color #%s
inactive_border_color #%s
bell_border_color #%s
active_tab_foreground #%s
active_tab_background #%s
inactive_tab_foreground #%s
inactive_tab_background #%s
color0 #%s
color1 #%s
color2 #%s
color3 #%s
color4 #%s
color5 #%s
color6 #%s
color7 #%s
color8 #%s
color9 #%s
color10 #%s
color11 #%s
color12 #%s
color13 #%s
color14 #%s
color15 #%s
`, t.Text, t.Base, opacity, t.OnAccent, t.Blue, t.Text, t.Base, t.Sky, t.Blue, t.Surface0, t.Yellow, t.OnAccent, t.Blue, t.Text, t.Surface0, t.Crust, t.Red, t.Green, t.Yellow, t.Blue, t.Mauve, t.Teal, t.Text, t.Overlay0, t.Red, t.Green, t.Yellow, t.Blue, t.Pink, t.Sky, t.Rosewater)
}

func renderRofi(t Theme) string {
	return fmt.Sprintf(`/* Generated by orgm-theme. */
* {
    bg-col: #%s;
    surface-col: #%s;
    border-col: #%s;
    selected-col: #%s;
    fg-col: #%s;
    fg-col2: #%s;
    prompt-fg: #%s;
}
`, t.MenuBG, t.QSCard, t.Blue, t.QSCardStrong, t.Text, t.Blue, t.OnAccent)
}

func renderFuzzel(t Theme) string {
	return fmt.Sprintf(`font=JetBrainsMono Nerd Font:size=12
icon-theme=%s
terminal=kitty
prompt="Apps> "
layer=overlay
width=34
lines=10
horizontal-pad=12
vertical-pad=10
inner-pad=6
line-height=22
fields=name,generic,comment,categories,filename,keywords
show-actions=yes

[colors]
background=%s
text=%sff
match=%sff
selection=%s
selection-text=%sff
selection-match=%sff
border=%sff

[border]
width=2
radius=10
`, t.IconTheme, t.MenuBG, t.Text, t.Blue, t.QSCardStrong, t.Text, t.Pink, t.Blue)
}

func renderWaybarPalette(t Theme) string {
	return fmt.Sprintf(`/* Generated by orgm-theme. */
@define-color base   #%s;
@define-color mantle #%s;
@define-color crust  #%s;
@define-color text     #%s;
@define-color subtext0 #%s;
@define-color subtext1 #%s;
@define-color surface0 #%s;
@define-color surface1 #%s;
@define-color surface2 #%s;
@define-color overlay0 #%s;
@define-color overlay1 #%s;
@define-color overlay2 #%s;
@define-color blue      #%s;
@define-color lavender  #%s;
@define-color sapphire  #%s;
@define-color sky       #%s;
@define-color teal      #%s;
@define-color green     #%s;
@define-color yellow    #%s;
@define-color peach     #%s;
@define-color maroon    #%s;
@define-color red       #%s;
@define-color mauve     #%s;
@define-color pink      #%s;
@define-color flamingo  #%s;
@define-color rosewater #%s;
@define-color panel_bg %s;
@define-color panel_border %s;
`, t.Base, t.Mantle, t.Crust, t.Text, t.Subtext0, t.Subtext1, t.Surface0, t.Surface1, t.Surface2, t.Overlay0, t.Overlay1, t.Overlay2, t.Blue, t.Mauve, t.Sky, t.Sky, t.Teal, t.Green, t.Yellow, t.Peach, t.Peach, t.Red, t.Mauve, t.Pink, t.Rosewater, t.Rosewater, cssColor(t.PanelBG), cssColor(t.Blue+"ff"))
}

func renderWaybarHyprPalette(t Theme) string {
	css := renderWaybarPalette(t)
	if t.ColorScheme == "prefer-light" {
		css += fmt.Sprintf(`window.top_bar#waybar,
window.bottom_bar#waybar {
  background: linear-gradient(to right, #%s 0%%, #%s 24%%, #%s 50%%, #%s 76%%, #%s 100%%);
}
`, t.Base, t.Mantle, t.Surface0, t.Mantle, t.Base)
		for _, name := range []string{"theme_toggle", "usb_devices", "nixclean", "hardware_fetch", "pi_status", "headset_reconnect", "logout_menu"} {
			css += fmt.Sprintf(`#custom-%s { background-image: url("icons/light/%s.svg"); }
`, name, name)
		}
		return css
	}
	css += fmt.Sprintf(`window.top_bar#waybar,
window.bottom_bar#waybar {
  background-color: %s;
}
`, cssColor(t.PanelBG))
	return css
}

func renderDock() string {
	return `/* Generated by orgm-theme. Keep dock as icons only in dark and light modes. */
window {
  background: transparent;
  border: none;
  box-shadow: none;
}
#box {
  background: transparent;
  border: none;
  box-shadow: none;
}
button,
button:hover,
button:focus,
button:checked,
button.active {
  background: transparent;
  border: none;
  box-shadow: none;
}
`
}

func renderSwayNC(t Theme) string {
	return renderWaybarPalette(t) + fmt.Sprintf("@define-color swaync_bg %s;\n", cssColor(t.Base+"cc"))
}

func renderFixedQuickshell(t Theme) string {
	switch t.Name {
	case "orgm-dark":
		return fixedQuickshellDark
	case "orgm-light":
		return fixedQuickshellLight
	default:
		return renderQuickshell(t)
	}
}

const fixedQuickshellDark = `{
  "overlay": "#000000",
  "border": "#33494d64",
  "text": "#cad3f5",
  "subtext": "#a5adcb",
  "muted": "#6e738d",
  "accent": "#8aadf4",
  "success": "#a6da95",
  "warning": "#eed49f",
  "error": "#ed8796",
  "pink": "#f5bde6",
  "button": "#22363a4f",
  "buttonStrong": "#33494d64",
  "buttonSoft": "#1e363a4f",
  "eventCard": "#2b363a4f",
  "hover": "#55363a4f",
  "outline": "#494d64",
  "onAccent": "#11111b",
  "disabled": "#363a4f"
}
`

const fixedQuickshellLight = `{
  "overlay": "#eff1f5",
  "border": "#ccd0dacc",
  "text": "#4c4f69",
  "subtext": "#6c6f85",
  "muted": "#9ca0b0",
  "accent": "#1e66f5",
  "success": "#40a02b",
  "warning": "#df8e1d",
  "error": "#d20f39",
  "pink": "#ea76cb",
  "button": "#e6e9efcc",
  "buttonStrong": "#ccd0dacc",
  "buttonSoft": "#dce0e8cc",
  "eventCard": "#eff1f5ee",
  "hover": "#bcc0ccaa",
  "outline": "#bcc0cc",
  "onAccent": "#eff1f5",
  "disabled": "#ccd0da"
}
`

func renderQuickshell(t Theme) string {
	return fmt.Sprintf(`{
  "overlay": "#%s",
  "border": "#%s",
  "text": "#%s",
  "subtext": "#%s",
  "muted": "#%s",
  "accent": "#%s",
  "success": "#%s",
  "warning": "#%s",
  "error": "#%s",
  "pink": "#%s",
  "button": "#%s",
  "buttonStrong": "#%s",
  "buttonSoft": "#%s",
  "eventCard": "#%s",
  "hover": "#%s",
  "outline": "#%s",
  "onAccent": "#%s",
  "disabled": "#%s"
}
`, opaqueHex(t.QSOverlay), t.QSCardStrong, t.Text, t.Subtext0, t.Overlay0, t.Blue, t.Green, t.Yellow, t.Red, t.Pink, t.QSCard, t.QSCardStrong, t.QSCardSoft, t.QSEvent, t.QSHover, t.Surface1, t.OnAccent, t.Surface0)
}

func renderGTKSettings(t Theme) string {
	preferDark := "false"
	if t.ColorScheme == "prefer-dark" {
		preferDark = "true"
	}
	return fmt.Sprintf(`[Settings]
gtk-theme-name=%s
gtk-application-prefer-dark-theme=%s
gtk-icon-theme-name=%s
gtk-cursor-theme-name=%s
gtk-cursor-theme-size=%s
gtk-font-name=Inter 11
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle=hintslight
gtk-xft-rgba=none
gtk-overlay-scrolling=true
`, t.GTKTheme, preferDark, t.IconTheme, t.CursorTheme, t.CursorSize)
}

func renderGTKCascade(t Theme) string {
	return fmt.Sprintf(`/* Generated by orgm-theme fallback colors. */
@define-color window_bg_color #%s;
@define-color window_fg_color #%s;
@define-color view_bg_color #%s;
@define-color view_fg_color #%s;
@define-color headerbar_bg_color #%s;
@define-color headerbar_fg_color #%s;
@define-color headerbar_backdrop_color @window_bg_color;
@define-color popover_bg_color #%s;
@define-color popover_fg_color #%s;
@define-color card_bg_color #%s;
@define-color card_fg_color #%s;
@define-color dialog_bg_color #%s;
@define-color dialog_fg_color #%s;
@define-color overview_bg_color #%s;
@define-color overview_fg_color #%s;
@define-color sidebar_bg_color #%s;
@define-color sidebar_fg_color #%s;
@define-color sidebar_backdrop_color @window_bg_color;
@define-color sidebar_border_color #%s;
@define-color secondary_sidebar_bg_color #%s;
@define-color secondary_sidebar_fg_color #%s;
@define-color accent_color #%s;
@define-color accent_bg_color #%s;
@define-color accent_fg_color #%s;

/* Keep sidebar tone aligned with main surface in GTK4/libadwaita apps (Nautilus). */
.nautilus-window .sidebar,
.nautilus-window placessidebar,
.nautilus-window .navigation-sidebar,
.sidebar,
.navigation-sidebar,
.side-stack {
  background-color: @sidebar_bg_color;
  color: @sidebar_fg_color;
}

:root {
  --accent-color: #%s;
  --accent-bg-color: #%s;
  --accent-fg-color: #%s;
  --window-bg-color: #%s;
  --window-fg-color: #%s;
  --view-bg-color: #%s;
  --view-fg-color: #%s;
  --headerbar-bg-color: #%s;
  --headerbar-fg-color: #%s;
  --headerbar-backdrop-color: @window_bg_color;
  --popover-bg-color: #%s;
  --popover-fg-color: #%s;
  --card-bg-color: #%s;
  --card-fg-color: #%s;
  --dialog-bg-color: #%s;
  --dialog-fg-color: #%s;
  --overview-bg-color: #%s;
  --overview-fg-color: #%s;
  --sidebar-bg-color: #%s;
  --sidebar-fg-color: #%s;
  --sidebar-backdrop-color: @window_bg_color;
  --sidebar-border-color: #%s;
  --secondary-sidebar-bg-color: #%s;
  --secondary-sidebar-fg-color: #%s;
}
`, t.Base, t.Text, t.Base, t.Text, t.Base, t.Text, t.Base, t.Text, t.Base, t.Text, t.Base, t.Text, t.Base, t.Text, t.Base, t.Text, t.Base, t.Base, t.Text, t.Blue, t.Blue, t.OnAccent, t.Blue, t.Blue, t.OnAccent, t.Base, t.Text, t.Base, t.Text, t.Base, t.Text, t.Base, t.Text, t.Base, t.Text, t.Base, t.Text, t.Base, t.Text, t.Base, t.Text, t.Base, t.Base, t.Text)
}

func renderCursorIndex(t Theme) string {
	return fmt.Sprintf(`[Icon Theme]
Inherits=%s
`, t.CursorTheme)
}

func renderQT(t Theme, configHome, qt string) (string, string) {
	conf := fmt.Sprintf(`[Appearance]
color_scheme_path=%s
custom_palette=true
icon_theme=%s
standard_dialogs=default
style=%s

[Fonts]
fixed="JetBrains Mono,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
general="Inter,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
`, filepath.Join(configHome, qt, "colors", "orgm-current.colors"), t.IconTheme, t.QTStyle)
	colors := fmt.Sprintf(`[General]
ColorScheme=ORGM Current
Name=ORGM Current
shadeSortColumn=true

[Colors:Window]
BackgroundNormal=#%s
BackgroundAlternate=#%s
ForegroundNormal=#%s
ForegroundInactive=#%s
DecorationFocus=#%s
DecorationHover=#%s

[Colors:View]
BackgroundNormal=#%s
BackgroundAlternate=#%s
ForegroundNormal=#%s
ForegroundInactive=#%s
DecorationFocus=#%s
DecorationHover=#%s

[Colors:Button]
BackgroundNormal=#%s
BackgroundAlternate=#%s
ForegroundNormal=#%s
ForegroundInactive=#%s
DecorationFocus=#%s
DecorationHover=#%s

[Colors:Selection]
BackgroundNormal=#%s
BackgroundAlternate=#%s
ForegroundNormal=#%s
ForegroundInactive=#%s

[WM]
activeBackground=#%s
activeForeground=#%s
inactiveBackground=#%s
inactiveForeground=#%s
`, t.Base, t.Mantle, t.Text, t.Subtext0, t.Blue, t.Blue, t.Base, t.Mantle, t.Text, t.Subtext0, t.Blue, t.Blue, t.Surface0, t.Surface1, t.Text, t.Subtext0, t.Blue, t.Blue, t.Blue, t.Blue, t.OnAccent, t.OnAccent, t.Surface0, t.Text, t.Mantle, t.Subtext0)
	return conf, colors
}

func renderKDEGlobals(t Theme) string {
	return fmt.Sprintf(`[General]
ColorScheme=ORGM Current
Name=ORGM Current

[Icons]
Theme=%s

[KDE]
SingleClick=false

[Colors:Window]
BackgroundNormal=#%s
ForegroundNormal=#%s

[Colors:View]
BackgroundNormal=#%s
ForegroundNormal=#%s

[Colors:Selection]
BackgroundNormal=#%s
ForegroundNormal=#%s
`, t.IconTheme, t.Base, t.Text, t.Base, t.Text, t.Blue, t.OnAccent)
}

func renderHyprScheme(t Theme) string {
	return fmt.Sprintf(`# Generated by orgm-theme. Hyprland-readable color variables.
$background = %s
$onBackground = %s
$surface = %s
$surfaceContainer = %s
$surfaceContainerHigh = %s
$onSurface = %s
$outline = %s
$primary = %s
$onPrimary = %s
$secondary = %s
$tertiary = %s
$error = %s
$term0 = %s
$term1 = %s
$term2 = %s
$term3 = %s
$term4 = %s
$term5 = %s
$term6 = %s
$term7 = %s
$term8 = %s
$term9 = %s
$term10 = %s
$term11 = %s
$term12 = %s
$term13 = %s
$term14 = %s
$term15 = %s
$text = %s
$subtext0 = %s
$overlay0 = %s
$surface0 = %s
$base = %s
`, t.Base, t.Text, t.Base, t.Mantle, t.Surface0, t.Text, t.Overlay0, t.Blue, t.OnAccent, t.Teal, t.Pink, t.Red, t.Crust, t.Red, t.Green, t.Yellow, t.Blue, t.Mauve, t.Teal, t.Text, t.Overlay0, t.Red, t.Green, t.Yellow, t.Blue, t.Pink, t.Sky, t.Rosewater, t.Text, t.Subtext0, t.Overlay0, t.Surface0, t.Base)
}

func renderConkyColors(t Theme) string {
	return fmt.Sprintf(`-- Generated by orgm-theme. Do not edit.
return {
  text      = "%s",
  accent    = "%s",
  secondary = "%s",
  warning   = "%s",
}
`, t.Text, t.Blue, t.Subtext0, t.Red)
}

func renderVesktop(t Theme) string {
	sr0, sg0, sb0, _ := hexToRGB(t.Surface0)
	sr1, sg1, sb1, _ := hexToRGB(t.Surface1)
	return fmt.Sprintf(`/* Generated by orgm-theme. Do not edit. */
.theme-dark,
.theme-light {
  --background-primary: #%s;
  --background-secondary: #%s;
  --background-secondary-alt: #%s;
  --background-tertiary: #%s;
  --background-accent: #%s;
  --background-floating: #%s;
  --channeltextarea-background: #%s;
  --background-modifier-hover: rgba(%d, %d, %d, 0.16);
  --background-modifier-active: rgba(%d, %d, %d, 0.24);
  --background-modifier-selected: rgba(%d, %d, %d, 0.32);
  --background-modifier-accent: rgba(%d, %d, %d, 0.48);
  --text-normal: #%s;
  --text-muted: #%s;
  --text-link: #%s;
  --interactive-normal: #%s;
  --interactive-hover: #%s;
  --interactive-active: #%s;
  --interactive-muted: #%s;
  --header-primary: #%s;
  --header-secondary: #%s;
  --channels-default: #%s;
  --channel-text-area-placeholder: #%s;
  --brand-experiment: #%s;
  --brand-360: #%s;
  --status-positive-text: #%s;
  --status-warning-text: #%s;
  --status-danger-text: #%s;
  --scrollbar-thin-thumb: #%s;
  --scrollbar-thin-track: transparent;
  --scrollbar-auto-thumb: #%s;
  --scrollbar-auto-track: #%s;
}
`,
		t.Base, t.Mantle, t.Crust, t.Crust, t.Surface0, t.Mantle, t.Surface0,
		sr0, sg0, sb0, sr0, sg0, sb0, sr0, sg0, sb0,
		sr1, sg1, sb1,
		t.Text, t.Subtext0, t.Blue,
		t.Text, t.Subtext1, t.Text, t.Overlay0,
		t.Text, t.Subtext0, t.Subtext0, t.Overlay0,
		t.Blue, t.Blue,
		t.Green, t.Yellow, t.Red,
		t.Surface1, t.Overlay1, t.Surface0)
}

func cssColor(hex string) string {
	h := strings.TrimPrefix(hex, "#")
	switch len(h) {
	case 6:
		return "#" + h
	case 8:
		red, green, blue, ok := hexToRGB(h)
		if !ok {
			return "#" + h
		}
		alpha, err := strconv.ParseInt(h[6:8], 16, 64)
		if err != nil {
			return "#" + h
		}
		alphaText := strings.TrimRight(strings.TrimRight(fmt.Sprintf("%.3f", float64(alpha)/255), "0"), ".")
		return fmt.Sprintf("rgba(%d, %d, %d, %s)", red, green, blue, alphaText)
	default:
		return "#" + h
	}
}

func hexToRGB(hex string) (int, int, int, bool) {
	h := strings.TrimPrefix(hex, "#")
	if len(h) < 6 {
		return 0, 0, 0, false
	}
	red, err := strconv.ParseInt(h[0:2], 16, 64)
	if err != nil {
		return 0, 0, 0, false
	}
	green, err := strconv.ParseInt(h[2:4], 16, 64)
	if err != nil {
		return 0, 0, 0, false
	}
	blue, err := strconv.ParseInt(h[4:6], 16, 64)
	if err != nil {
		return 0, 0, 0, false
	}
	return int(red), int(green), int(blue), true
}

func opaqueHex(hexValue string) string {
	h := strings.TrimPrefix(strings.TrimSpace(hexValue), "#")
	if len(h) == 8 {
		return h[:6]
	}
	return h
}
