package theme

import (
	"strings"
	"testing"
)

func TestResolvePaletteUsesRequestedDarkAndLightModes(t *testing.T) {
	theme := planTestTheme()

	dark, darkWarning, err := ResolvePalette(theme, "dark", WallpaperInfo{})
	if err != nil {
		t.Fatalf("ResolvePalette(dark) error = %v", err)
	}
	light, lightWarning, err := ResolvePalette(theme, "light", WallpaperInfo{})
	if err != nil {
		t.Fatalf("ResolvePalette(light) error = %v", err)
	}

	if got, want := dark.Mode, "dark"; got != want {
		t.Fatalf("dark mode = %q, want %q", got, want)
	}
	if got, want := dark.Palette.Background, "#000000"; got != want {
		t.Fatalf("dark background = %q, want %q", got, want)
	}
	if got := darkWarning; got != "" {
		t.Fatalf("dark warning = %q, want empty", got)
	}
	if got, want := light.Mode, "light"; got != want {
		t.Fatalf("light mode = %q, want %q", got, want)
	}
	if got, want := light.Palette.Background, "#ffffff"; got != want {
		t.Fatalf("light background = %q, want %q", got, want)
	}
	if got := lightWarning; got != "" {
		t.Fatalf("light warning = %q, want empty", got)
	}
}

func TestResolvePaletteAutoUsesBrightnessOrFallsBackToDefaultModeWithWarning(t *testing.T) {
	theme := planTestTheme()

	light, lightWarning, err := ResolvePalette(theme, "auto", WallpaperInfo{Brightness: 0.80, BrightnessKnown: true})
	if err != nil {
		t.Fatalf("ResolvePalette(auto bright) error = %v", err)
	}
	dark, darkWarning, err := ResolvePalette(theme, "auto", WallpaperInfo{Brightness: 0.20, BrightnessKnown: true})
	if err != nil {
		t.Fatalf("ResolvePalette(auto dark) error = %v", err)
	}
	fallback, fallbackWarning, err := ResolvePalette(theme, "auto", WallpaperInfo{})
	if err != nil {
		t.Fatalf("ResolvePalette(auto unknown) error = %v", err)
	}

	if got, want := light.Mode, "light"; got != want {
		t.Fatalf("bright auto mode = %q, want %q", got, want)
	}
	if got, want := dark.Mode, "dark"; got != want {
		t.Fatalf("dark auto mode = %q, want %q", got, want)
	}
	if lightWarning != "" || darkWarning != "" {
		t.Fatalf("brightness warnings = %q/%q, want empty", lightWarning, darkWarning)
	}
	if got, want := fallback.Mode, "dark"; got != want {
		t.Fatalf("fallback auto mode = %q, want %q", got, want)
	}
	if got, want := fallbackWarning, "auto mode brightness unavailable; using default mode dark"; got != want {
		t.Fatalf("fallback warning = %q, want %q", got, want)
	}
}

func TestBuildApplyPlanReturnsWritesReloadsAndWarningsForSupportedTargets(t *testing.T) {
	theme := planTestTheme()
	theme.Targets = map[string]map[string]string{
		"hypr":     {"mode": "generated"},
		"chromium": {"mode": "export"},
	}

	plan, err := BuildApplyPlan(theme, PlanOptions{Mode: "dark", StateHome: "/state", CacheHome: "/cache"})

	if err != nil {
		t.Fatalf("BuildApplyPlan() error = %v", err)
	}
	if got, want := plan.ThemeID, "neutral"; got != want {
		t.Fatalf("ThemeID = %q, want %q", got, want)
	}
	if got, want := plan.Mode, "dark"; got != want {
		t.Fatalf("Mode = %q, want %q", got, want)
	}
	if len(plan.Writes) != 3 {
		t.Fatalf("writes length = %d, want 3: %#v", len(plan.Writes), plan.Writes)
	}
	if got, want := plan.Writes[0].Path, "/state/orgm-hypr/theme/current/palette.json"; got != want {
		t.Fatalf("write path = %q, want %q", got, want)
	}
	if !strings.Contains(string(plan.Writes[0].Content), "Generated by orgm-hypr theme") {
		t.Fatalf("write content missing generated marker: %q", string(plan.Writes[0].Content))
	}
	if got, want := plan.Writes[1].Path, "/state/orgm-hypr/theme/exports/chromium/neutral-dark/manifest.json"; got != want {
		t.Fatalf("chromium manifest path = %q, want %q", got, want)
	}
	if !strings.Contains(string(plan.Writes[1].Content), `"manifest_version": 3`) {
		t.Fatalf("chromium manifest content = %q, want manifest version", string(plan.Writes[1].Content))
	}
	if got, want := plan.Writes[2].Path, "/state/orgm-hypr/theme/current/hypr/colors.conf"; got != want {
		t.Fatalf("hypr colors path = %q, want %q", got, want)
	}
	if !strings.Contains(string(plan.Writes[2].Content), "$accent = rgba(7777ffff)") {
		t.Fatalf("hypr colors content = %q, want accent", string(plan.Writes[2].Content))
	}
	if len(plan.Reloads) != 1 || plan.Reloads[0].Target != "hypr" || plan.Reloads[0].Command != "hyprctl reload" {
		t.Fatalf("reloads = %#v, want hyprctl reload", plan.Reloads)
	}
	if len(plan.Warnings) != 2 || !strings.Contains(plan.Warnings[0], "generated theme export only") || !strings.Contains(plan.Warnings[1], "source generated colors.conf") {
		t.Fatalf("warnings = %#v, want chromium manual export and hypr source warnings", plan.Warnings)
	}
}

func TestBuildApplyPlanRejectsUnknownTargetsClearly(t *testing.T) {
	theme := planTestTheme()
	theme.Targets = map[string]map[string]string{"bogus": {"mode": "generated"}}

	_, err := BuildApplyPlan(theme, PlanOptions{Mode: "dark", StateHome: "/state", CacheHome: "/cache"})

	if err == nil {
		t.Fatal("BuildApplyPlan() error = nil, want unknown target error")
	}
	if got, want := err.Error(), `invalid target "bogus"`; !strings.Contains(got, want) {
		t.Fatalf("error = %q, want substring %q", got, want)
	}
}

func planTestTheme() Theme {
	return Theme{
		ID:          "neutral",
		Name:        "Neutral",
		DefaultMode: "dark",
		Palettes: map[string]Palette{
			"dark":  validPalette("#000000", "#eeeeee", "#7777ff"),
			"light": validPalette("#ffffff", "#111111", "#333388"),
		},
	}
}
