package theme

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

const GeneratedMarker = "Generated by orgm-hypr theme"

type WallpaperInfo struct {
	Brightness      float64
	BrightnessKnown bool
}

type ResolvedPalette struct {
	Mode    string
	Palette Palette
}

type PlanOptions struct {
	Mode       string
	StateHome  string
	CacheHome  string
	ConfigHome string
	Wallpaper  WallpaperInfo
}

type ApplyPlan struct {
	ThemeID  string
	Mode     string
	Writes   []PlannedWrite
	Reloads  []PlannedReload
	Warnings []string
}

type PlannedWrite struct {
	Target  string
	Path    string
	Content []byte
	Mode    int
}

type PlannedReload struct {
	Target  string
	Command string
}

func ResolvePalette(theme Theme, mode string, wallpaper WallpaperInfo) (ResolvedPalette, string, error) {
	requested := mode
	if requested == "" {
		requested = theme.DefaultMode
	}
	if requested == "auto" {
		if wallpaper.BrightnessKnown {
			if wallpaper.Brightness >= 0.5 {
				requested = "light"
			} else {
				requested = "dark"
			}
		} else {
			requested = theme.DefaultMode
			warning := fmt.Sprintf("auto mode brightness unavailable; using default mode %s", requested)
			resolved, _, err := ResolvePalette(theme, requested, WallpaperInfo{})
			return resolved, warning, err
		}
	}
	if !validMode(requested) || requested == "auto" {
		return ResolvedPalette{}, "", fmt.Errorf("mode must be dark, light, or auto")
	}
	palette, ok := theme.Palettes[requested]
	if !ok {
		return ResolvedPalette{}, "", fmt.Errorf("theme %q missing palette %q", theme.ID, requested)
	}
	return ResolvedPalette{Mode: requested, Palette: palette}, "", nil
}

func BuildApplyPlan(theme Theme, opts PlanOptions) (ApplyPlan, error) {
	resolved, warning, err := ResolvePalette(theme, opts.Mode, opts.Wallpaper)
	if err != nil {
		return ApplyPlan{}, err
	}
	plan := ApplyPlan{ThemeID: theme.ID, Mode: resolved.Mode}
	if warning != "" {
		plan.Warnings = append(plan.Warnings, warning)
	}

	content, err := paletteContent(theme.ID, resolved)
	if err != nil {
		return ApplyPlan{}, err
	}
	plan.Writes = append(plan.Writes, PlannedWrite{
		Target:  "hypr",
		Path:    filepath.Join(opts.StateHome, "orgm-hypr", "theme", "current", "palette.json"),
		Content: content,
		Mode:    0o600,
	})
	plan.Reloads = append(plan.Reloads, PlannedReload{Target: "hypr", Command: "hyprctl reload"})

	targetNames := make([]string, 0, len(theme.Targets))
	for target := range theme.Targets {
		targetNames = append(targetNames, target)
	}
	sort.Strings(targetNames)
	for _, target := range targetNames {
		switch target {
		case "hypr":
			plan.Writes = append(plan.Writes, renderHypr(resolved, opts)...)
			plan.Warnings = append(plan.Warnings, "hypr: source generated colors.conf or read palette.json from Hyprland Lua to apply colors")
		case "waybar":
			plan.Writes = append(plan.Writes, renderWaybar(resolved, opts)...)
			plan.Reloads = append(plan.Reloads, PlannedReload{Target: "waybar", Command: "pkill -SIGUSR2 waybar"})
			plan.Warnings = append(plan.Warnings, fmt.Sprintf("waybar: import %s from style.css and reload Waybar", filepath.Join(opts.ConfigHome, "waybar-hypr", "orgm-hypr-theme.css")))
		case "nwg-dock":
			plan.Writes = append(plan.Writes, renderNWGDock(resolved, opts)...)
			plan.Reloads = append(plan.Reloads, PlannedReload{Target: "nwg-dock", Command: "hypr-nwg-dock restart"})
			plan.Warnings = append(plan.Warnings, fmt.Sprintf("nwg-dock: point nwg-dock-hyprland to %s and restart dock", filepath.Join(opts.ConfigHome, "nwg-dock-hyprland", "orgm-hypr-theme.css")))
		case "gtk":
			plan.Writes = append(plan.Writes, renderGTK(resolved, opts)...)
			plan.Warnings = append(plan.Warnings, "gtk: generated settings/CSS require GTK apps to restart or import the CSS manually")
		case "qt":
			plan.Writes = append(plan.Writes, renderQt(resolved, opts)...)
			plan.Warnings = append(plan.Warnings, "qt: generated qt5ct/qt6ct files require selecting orgm-hypr config or restarting Qt apps")
		case "fuzzel":
			plan.Writes = append(plan.Writes, renderFuzzel(resolved, opts)...)
			plan.Warnings = append(plan.Warnings, "fuzzel: include or pass generated theme file manually; existing config was not modified")
			warnIfMissingConfigDir(&plan, opts, "fuzzel", "fuzzel")
		case "rofi":
			plan.Writes = append(plan.Writes, renderRofi(resolved, opts)...)
			plan.Warnings = append(plan.Warnings, "rofi: import generated theme from config.rasi manually; existing config was not modified")
			warnIfMissingConfigDir(&plan, opts, "rofi", "rofi")
		case "kitty":
			plan.Writes = append(plan.Writes, renderKitty(resolved, opts)...)
			plan.Warnings = append(plan.Warnings, "kitty: add include orgm-hypr-theme.conf to kitty.conf manually; existing config was not modified")
			warnIfMissingConfigDir(&plan, opts, "kitty", "kitty")
		case "yazi":
			plan.Writes = append(plan.Writes, renderYazi(resolved, opts)...)
			plan.Warnings = append(plan.Warnings, "yazi: generated theme.toml may replace Yazi theme file; review before enabling")
			warnIfMissingConfigDir(&plan, opts, "yazi", "yazi")
		case "helix":
			plan.Writes = append(plan.Writes, renderHelix(resolved, opts)...)
			plan.Warnings = append(plan.Warnings, "helix: set theme = \"orgm-hypr\" in config.toml manually; existing config was not modified")
			warnIfMissingConfigDir(&plan, opts, "helix", "helix")
		case "kvantum":
			plan.Writes = append(plan.Writes, renderKvantum(resolved, opts)...)
			plan.Warnings = append(plan.Warnings, "kvantum: select orgm-hypr in Kvantum Manager manually; existing config was not modified")
			warnIfMissingConfigDir(&plan, opts, "kvantum", "Kvantum")
		case "kde":
			plan.Writes = append(plan.Writes, renderKDE(resolved, opts)...)
			plan.Warnings = append(plan.Warnings, "kde: import generated kdeglobals.orgm-hypr manually; existing config was not modified")
			warnIfMissingConfigDir(&plan, opts, "kde", "")
		case "chromium":
			plan.Writes = append(plan.Writes, renderChromium(theme, resolved, opts)...)
			plan.Warnings = append(plan.Warnings, "chromium: generated theme export only; load unpacked extension manually and restart Chromium if needed; profile was not modified")
		case "zen":
			plan.Writes = append(plan.Writes, renderZen(theme, resolved, opts)...)
			plan.Warnings = append(plan.Warnings, "zen: generated browser export notes only; copy files manually after reviewing profile path; profile was not modified")
		default:
			return ApplyPlan{}, fmt.Errorf("invalid target %q", target)
		}
	}
	return plan, nil
}

func renderHypr(resolved ResolvedPalette, opts PlanOptions) []PlannedWrite {
	content := fmt.Sprintf(`# %s
# mode: %s
$background = rgba(%sff)
$surface = rgba(%sff)
$surface_alt = rgba(%sff)
$foreground = rgba(%sff)
$muted = rgba(%sff)
$accent = rgba(%sff)
$accent2 = rgba(%sff)
$border = rgba(%sff)
$urgent = rgba(%sff)
$success = rgba(%sff)
`, GeneratedMarker, resolved.Mode,
		hexNoHash(resolved.Palette.Background), hexNoHash(resolved.Palette.Surface), hexNoHash(resolved.Palette.SurfaceAlt),
		hexNoHash(resolved.Palette.Foreground), hexNoHash(resolved.Palette.Muted), hexNoHash(resolved.Palette.Accent),
		hexNoHash(resolved.Palette.Accent2), hexNoHash(resolved.Palette.Border), hexNoHash(resolved.Palette.Urgent), hexNoHash(resolved.Palette.Success))
	return []PlannedWrite{{Target: "hypr", Path: filepath.Join(opts.StateHome, "orgm-hypr", "theme", "current", "hypr", "colors.conf"), Content: []byte(content), Mode: 0o600}}
}

func renderWaybar(resolved ResolvedPalette, opts PlanOptions) []PlannedWrite {
	p := resolved.Palette
	content := fmt.Sprintf(`/* %s */
@define-color background %s;
@define-color surface %s;
@define-color surface_alt %s;
@define-color foreground %s;
@define-color muted %s;
@define-color accent %s;
@define-color accent2 %s;
@define-color border %s;
@define-color urgent %s;
@define-color success %s;
`, GeneratedMarker, p.Background, p.Surface, p.SurfaceAlt, p.Foreground, p.Muted, p.Accent, p.Accent2, p.Border, p.Urgent, p.Success)
	return []PlannedWrite{{Target: "waybar", Path: filepath.Join(opts.ConfigHome, "waybar-hypr", "orgm-hypr-theme.css"), Content: []byte(content), Mode: 0o600}}
}

func renderNWGDock(resolved ResolvedPalette, opts PlanOptions) []PlannedWrite {
	p := resolved.Palette
	r, g, b := rgbValues(p.Background)
	content := fmt.Sprintf(`/* %s */
window {
	background: rgba(%d, %d, %d, 0.88);
	border: 1px solid %s;
	border-radius: 10px;
}

button {
	color: %s;
	background: transparent;
}

button:hover,
button:focus,
button:checked,
button.active {
	background: %s;
	color: %s;
}
`, GeneratedMarker, r, g, b, p.Accent, p.Foreground, p.SurfaceAlt, p.Foreground)
	return []PlannedWrite{{Target: "nwg-dock", Path: filepath.Join(opts.ConfigHome, "nwg-dock-hyprland", "orgm-hypr-theme.css"), Content: []byte(content), Mode: 0o600}}
}

func renderGTK(resolved ResolvedPalette, opts PlanOptions) []PlannedWrite {
	p := resolved.Palette
	dark := resolved.Mode == "dark"
	preferDark := "false"
	themeName := "Adwaita"
	if dark {
		preferDark = "true"
		themeName = "Adwaita-dark"
	}
	settings := fmt.Sprintf(`# %s
[Settings]
gtk-application-prefer-dark-theme=%s
gtk-theme-name=%s
gtk-icon-theme-name=Adwaita
gtk-cursor-theme-name=Adwaita
`, GeneratedMarker, preferDark, themeName)
	css := fmt.Sprintf(`/* %s */
@define-color accent_color %s;
@define-color window_bg_color %s;
@define-color window_fg_color %s;
@define-color view_bg_color %s;
@define-color view_fg_color %s;
@define-color headerbar_bg_color %s;
@define-color borders %s;
@define-color error_color %s;
@define-color success_color %s;
`, GeneratedMarker, p.Accent, p.Background, p.Foreground, p.Surface, p.Foreground, p.SurfaceAlt, p.Border, p.Urgent, p.Success)
	writes := []PlannedWrite{}
	for _, version := range []string{"gtk-3.0", "gtk-4.0"} {
		writes = append(writes,
			PlannedWrite{Target: "gtk", Path: filepath.Join(opts.ConfigHome, version, "orgm-hypr-settings.ini"), Content: []byte(settings), Mode: 0o600},
			PlannedWrite{Target: "gtk", Path: filepath.Join(opts.ConfigHome, version, "orgm-hypr-theme.css"), Content: []byte(css), Mode: 0o600},
		)
	}
	return writes
}

func renderQt(resolved ResolvedPalette, opts PlanOptions) []PlannedWrite {
	p := resolved.Palette
	style := "Fusion"
	if resolved.Mode == "dark" {
		style = "Darkly"
	}
	colors := fmt.Sprintf(`# %s
[ColorScheme]
name=orgm-hypr-%s
active_colors=%s, %s, %s, %s, %s, %s, %s
disabled_colors=%s, %s, %s, %s, %s, %s, %s
inactive_colors=%s, %s, %s, %s, %s, %s, %s
`, GeneratedMarker, resolved.Mode,
		p.Foreground, p.Background, p.SurfaceAlt, p.Surface, p.Surface, p.Foreground, p.Accent,
		p.Muted, p.Background, p.SurfaceAlt, p.Surface, p.Surface, p.Muted, p.Border,
		p.Foreground, p.Background, p.SurfaceAlt, p.Surface, p.Surface, p.Foreground, p.Accent)
	writes := []PlannedWrite{}
	for _, version := range []string{"qt5ct", "qt6ct"} {
		colorPath := filepath.Join(opts.ConfigHome, version, "colors", "orgm-hypr.colors")
		conf := fmt.Sprintf(`# %s
[Appearance]
color_scheme_path=%s
custom_palette=true
icon_theme=Adwaita
standard_dialogs=default
style=%s
`, GeneratedMarker, colorPath, style)
		writes = append(writes,
			PlannedWrite{Target: "qt", Path: colorPath, Content: []byte(colors), Mode: 0o600},
			PlannedWrite{Target: "qt", Path: filepath.Join(opts.ConfigHome, version, "orgm-hypr.conf"), Content: []byte(conf), Mode: 0o600},
		)
	}
	return writes
}

func renderFuzzel(resolved ResolvedPalette, opts PlanOptions) []PlannedWrite {
	p := resolved.Palette
	content := fmt.Sprintf(`# %s
[colors]
background=000000dd
text=%sff
prompt=%sff
placeholder=%sff
input=%sff
match=%sff
selection=%sdd
selection-text=%sff
selection-match=%sff
border=%sff
`, GeneratedMarker, hexNoHash(p.Foreground), hexNoHash(p.Accent), hexNoHash(p.Muted), hexNoHash(p.Foreground), hexNoHash(p.Accent), hexNoHash(p.SurfaceAlt), hexNoHash(p.Foreground), hexNoHash(p.Accent2), hexNoHash(p.Accent))
	return []PlannedWrite{{Target: "fuzzel", Path: filepath.Join(opts.ConfigHome, "fuzzel", "orgm-hypr-theme.ini"), Content: []byte(content), Mode: 0o600}}
}

func renderRofi(resolved ResolvedPalette, opts PlanOptions) []PlannedWrite {
	p := resolved.Palette
	r, g, b := rgbValues(p.SurfaceAlt)
	content := fmt.Sprintf(`/* %s */
* {
    background: rgba(0, 0, 0, 0.86);
    foreground: %s;
    selected: rgba(%d, %d, %d, 0.86);
    active: %s;
    urgent: %s;
    border: %s;
}

window {
    background-color: @background;
    border-color: @border;
    border-radius: 15px;
}

mainbox,
inputbar,
listview,
element,
element-icon,
element-text {
    background-color: transparent;
}

entry {
    background-color: @selected;
    text-color: @foreground;
}

element selected,
element-text selected,
element-icon selected {
    background-color: @selected;
    text-color: @foreground;
}
`, GeneratedMarker, p.Foreground, r, g, b, p.Success, p.Urgent, p.Accent)
	return []PlannedWrite{{Target: "rofi", Path: filepath.Join(opts.ConfigHome, "rofi", "orgm-hypr-theme.rasi"), Content: []byte(content), Mode: 0o600}}
}

func renderKitty(resolved ResolvedPalette, opts PlanOptions) []PlannedWrite {
	p := resolved.Palette
	content := fmt.Sprintf(`# %s
background %s
foreground %s
selection_background %s
selection_foreground %s
cursor %s
url_color %s
active_border_color %s
inactive_border_color %s
bell_border_color %s
`, GeneratedMarker, p.Background, p.Foreground, p.SurfaceAlt, p.Foreground, p.Accent, p.Accent2, p.Accent, p.Border, p.Urgent)
	return []PlannedWrite{{Target: "kitty", Path: filepath.Join(opts.ConfigHome, "kitty", "orgm-hypr-theme.conf"), Content: []byte(content), Mode: 0o600}}
}

func renderYazi(resolved ResolvedPalette, opts PlanOptions) []PlannedWrite {
	p := resolved.Palette
	content := fmt.Sprintf(`# %s
syntect_theme = "base16-orgm-hypr"

[manager]
cwd = { fg = "%s" }
hovered = { fg = "%s", bg = "%s" }
preview_hovered = { underline = true }

[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "%s", bg = "%s" }

[filetype]
rules = [
  { mime = "inode/directory", fg = "%s" },
]
`, GeneratedMarker, p.Accent, p.Foreground, p.SurfaceAlt, p.SurfaceAlt, p.Background, p.Accent)
	return []PlannedWrite{{Target: "yazi", Path: filepath.Join(opts.ConfigHome, "yazi", "theme.toml"), Content: []byte(content), Mode: 0o600}}
}

func renderHelix(resolved ResolvedPalette, opts PlanOptions) []PlannedWrite {
	p := resolved.Palette
	content := fmt.Sprintf(`# %s
"ui.background" = { bg = "background" }
"ui.text" = { fg = "foreground" }
"ui.selection" = { bg = "surface_alt" }
"ui.cursor" = { fg = "background", bg = "accent" }
"ui.statusline" = { fg = "foreground", bg = "surface" }
"warning" = "urgent"
"error" = "urgent"

[palette]
background = "%s"
surface = "%s"
surface_alt = "%s"
foreground = "%s"
muted = "%s"
accent = "%s"
urgent = "%s"
success = "%s"
`, GeneratedMarker, p.Background, p.Surface, p.SurfaceAlt, p.Foreground, p.Muted, p.Accent, p.Urgent, p.Success)
	return []PlannedWrite{{Target: "helix", Path: filepath.Join(opts.ConfigHome, "helix", "themes", "orgm-hypr.toml"), Content: []byte(content), Mode: 0o600}}
}

func renderKvantum(resolved ResolvedPalette, opts PlanOptions) []PlannedWrite {
	p := resolved.Palette
	content := fmt.Sprintf(`# %s
[General]
base.color=%s
text.color=%s
highlight.color=%s
highlight.text.color=%s
window.color=%s
alternate.color=%s
disabled.text.color=%s
contrast=%s
`, GeneratedMarker, p.Background, p.Foreground, p.Accent, p.Foreground, p.Surface, p.SurfaceAlt, p.Muted, p.Border)
	return []PlannedWrite{{Target: "kvantum", Path: filepath.Join(opts.ConfigHome, "Kvantum", "orgm-hypr", "orgm-hypr.kvconfig"), Content: []byte(content), Mode: 0o600}}
}

func renderKDE(resolved ResolvedPalette, opts PlanOptions) []PlannedWrite {
	p := resolved.Palette
	br, bg, bb := rgbValues(p.Background)
	fr, fg, fb := rgbValues(p.Foreground)
	sr, sg, sb := rgbValues(p.Surface)
	ar, ag, ab := rgbValues(p.Accent)
	content := fmt.Sprintf(`# %s
[Colors:Window]
BackgroundNormal=%d,%d,%d
ForegroundNormal=%d,%d,%d

[Colors:View]
BackgroundNormal=%d,%d,%d
ForegroundNormal=%d,%d,%d

[Colors:Selection]
BackgroundNormal=%d,%d,%d
ForegroundNormal=%d,%d,%d
`, GeneratedMarker, br, bg, bb, fr, fg, fb, sr, sg, sb, fr, fg, fb, ar, ag, ab, fr, fg, fb)
	return []PlannedWrite{{Target: "kde", Path: filepath.Join(opts.ConfigHome, "kdeglobals.orgm-hypr"), Content: []byte(content), Mode: 0o600}}
}

func renderChromium(theme Theme, resolved ResolvedPalette, opts PlanOptions) []PlannedWrite {
	p := resolved.Palette
	exportDir := filepath.Join(opts.StateHome, "orgm-hypr", "theme", "exports", "chromium", theme.ID+"-"+resolved.Mode)
	manifest := struct {
		Marker          string `json:"_comment"`
		ManifestVersion int    `json:"manifest_version"`
		Name            string `json:"name"`
		Version         string `json:"version"`
		Theme           struct {
			Colors map[string][]int  `json:"colors"`
			Images map[string]string `json:"images,omitempty"`
		} `json:"theme"`
	}{
		Marker:          GeneratedMarker,
		ManifestVersion: 3,
		Name:            fmt.Sprintf("orgm-hypr %s %s", theme.ID, resolved.Mode),
		Version:         "1.0.0",
	}
	manifest.Theme.Colors = map[string][]int{
		"bookmark_text":       rgbSlice(p.Foreground),
		"button_background":   rgbSlice(p.SurfaceAlt),
		"frame":               rgbSlice(p.Accent),
		"frame_inactive":      rgbSlice(p.Surface),
		"ntp_background":      rgbSlice(p.Background),
		"ntp_text":            rgbSlice(p.Foreground),
		"tab_background_text": rgbSlice(p.Muted),
		"tab_text":            rgbSlice(p.Foreground),
		"toolbar":             rgbSlice(p.Surface),
		"toolbar_button_icon": rgbSlice(p.Foreground),
	}
	writes := []PlannedWrite{}
	if theme.Wallpaper.Path != "" {
		if wallpaper, err := os.ReadFile(theme.Wallpaper.Path); err == nil {
			ext := filepath.Ext(theme.Wallpaper.Path)
			if ext == "" {
				ext = ".png"
			}
			assetName := "wallpaper" + ext
			manifest.Theme.Images = map[string]string{"theme_ntp_background": assetName}
			writes = append(writes, PlannedWrite{Target: "chromium", Path: filepath.Join(exportDir, assetName), Content: wallpaper, Mode: 0o600})
		}
	}
	data, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return nil
	}
	manifestWrite := PlannedWrite{Target: "chromium", Path: filepath.Join(exportDir, "manifest.json"), Content: append(data, '\n'), Mode: 0o600}
	return append([]PlannedWrite{manifestWrite}, writes...)
}

func renderZen(theme Theme, resolved ResolvedPalette, opts PlanOptions) []PlannedWrite {
	p := resolved.Palette
	exportDir := filepath.Join(opts.StateHome, "orgm-hypr", "theme", "exports", "zen", theme.ID+"-"+resolved.Mode)
	readme := fmt.Sprintf(`# orgm-hypr Zen Browser theme export

%s

Mode: %s
Theme: %s

No Zen profile files were modified.

Manual steps:
1. Open about:profiles in Zen Browser and choose the profile to theme.
2. Back up the profile's chrome/userChrome.css if it exists.
3. Copy userChrome.css from this directory into that profile's chrome directory.
4. Restart Zen Browser.

Copy userChrome.css manually only after backing up your selected profile.
`, GeneratedMarker, resolved.Mode, theme.ID)
	css := fmt.Sprintf(`/* %s */
:root {
  --orgm-hypr-background: %s;
  --orgm-hypr-surface: %s;
  --orgm-hypr-foreground: %s;
  --orgm-hypr-muted: %s;
  --orgm-hypr-accent: %s;
  --orgm-hypr-border: %s;
}

#navigator-toolbox,
#TabsToolbar,
#nav-bar {
  background-color: var(--orgm-hypr-background) !important;
  color: var(--orgm-hypr-foreground) !important;
}

tab[selected="true"] .tab-background {
  background-color: var(--orgm-hypr-surface) !important;
  outline: 1px solid var(--orgm-hypr-accent) !important;
}
`, GeneratedMarker, p.Background, p.Surface, p.Foreground, p.Muted, p.Accent, p.Border)
	return []PlannedWrite{
		{Target: "zen", Path: filepath.Join(exportDir, "README.md"), Content: []byte(readme), Mode: 0o600},
		{Target: "zen", Path: filepath.Join(exportDir, "userChrome.css"), Content: []byte(css), Mode: 0o600},
	}
}

func rgbSlice(value string) []int {
	r, g, b := rgbValues(value)
	return []int{r, g, b}
}

func warnIfMissingConfigDir(plan *ApplyPlan, opts PlanOptions, target, dir string) {
	path := filepath.Join(opts.ConfigHome, dir)
	if dir == "" {
		path = filepath.Join(opts.ConfigHome, "kdeglobals")
	}
	info, err := os.Stat(path)
	if err == nil && (dir == "" || info.IsDir()) {
		return
	}
	plan.Warnings = append(plan.Warnings, fmt.Sprintf("%s: no existing config directory found; generated file is a safe pointer only", target))
}

func hexNoHash(value string) string {
	return strings.TrimPrefix(value, "#")
}

func rgbValues(value string) (int, int, int) {
	hex := strings.TrimPrefix(value, "#")
	return hexByte(hex[0:2]), hexByte(hex[2:4]), hexByte(hex[4:6])
}

func hexByte(value string) int {
	parsed, _ := strconv.ParseInt(value, 16, 0)
	return int(parsed)
}

func paletteContent(themeID string, resolved ResolvedPalette) ([]byte, error) {
	payload := struct {
		Marker  string  `json:"_comment"`
		ThemeID string  `json:"themeID"`
		Mode    string  `json:"mode"`
		Palette Palette `json:"palette"`
	}{
		Marker:  GeneratedMarker,
		ThemeID: themeID,
		Mode:    resolved.Mode,
		Palette: resolved.Palette,
	}
	data, err := json.MarshalIndent(payload, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(data, '\n'), nil
}
