package theme

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestBuildApplyPlanRendersCoreDesktopTargets(t *testing.T) {
	theme := planTestTheme()
	theme.Targets = map[string]map[string]string{
		"gtk":      {"mode": "generated"},
		"hypr":     {"mode": "generated"},
		"nwg-dock": {"mode": "generated"},
		"qt":       {"mode": "generated"},
		"waybar":   {"mode": "generated"},
	}

	plan, err := BuildApplyPlan(theme, PlanOptions{Mode: "dark", StateHome: "/state", CacheHome: "/cache", ConfigHome: "/config"})

	if err != nil {
		t.Fatalf("BuildApplyPlan() error = %v", err)
	}
	assertPlanWriteContains(t, plan, "hypr", filepath.Join("/state", "orgm-hypr", "theme", "current", "hypr", "colors.conf"), []string{
		"# Generated by orgm-hypr theme",
		"$background = rgba(000000ff)",
		"$foreground = rgba(eeeeeeff)",
		"$accent = rgba(7777ffff)",
	})
	assertPlanWriteContains(t, plan, "waybar", filepath.Join("/config", "waybar-hypr", "orgm-hypr-theme.css"), []string{
		"/* Generated by orgm-hypr theme */",
		"@define-color background #000000;",
		"@define-color foreground #eeeeee;",
		"@define-color accent #7777ff;",
	})
	assertPlanWriteContains(t, plan, "nwg-dock", filepath.Join("/config", "nwg-dock-hyprland", "orgm-hypr-theme.css"), []string{
		"window {",
		"background: rgba(0, 0, 0, 0.88);",
		"border: 1px solid #7777ff;",
	})
	assertPlanWriteContains(t, plan, "gtk", filepath.Join("/config", "gtk-3.0", "orgm-hypr-settings.ini"), []string{
		"[Settings]",
		"gtk-application-prefer-dark-theme=true",
		"gtk-theme-name=Adwaita-dark",
	})
	assertPlanWriteContains(t, plan, "gtk", filepath.Join("/config", "gtk-4.0", "orgm-hypr-theme.css"), []string{
		"@define-color accent_color #7777ff;",
		"@define-color window_bg_color #000000;",
	})
	assertPlanWriteContains(t, plan, "qt", filepath.Join("/config", "qt5ct", "colors", "orgm-hypr.colors"), []string{
		"[ColorScheme]",
		"active_colors=#eeeeee, #000000, #353438, #201f23, #201f23, #eeeeee, #7777ff",
	})
	assertPlanWriteContains(t, plan, "qt", filepath.Join("/config", "qt6ct", "orgm-hypr.conf"), []string{
		"[Appearance]",
		"color_scheme_path=/config/qt6ct/colors/orgm-hypr.colors",
		"custom_palette=true",
	})
	assertPlanReload(t, plan, "hypr", "hyprctl reload")
	assertPlanReload(t, plan, "waybar", "pkill -SIGUSR2 waybar")
	assertPlanReload(t, plan, "nwg-dock", "hypr-nwg-dock restart")
}

func TestBuildApplyPlanRendersAppTargets(t *testing.T) {
	configHome := t.TempDir()
	for _, dir := range []string{"fuzzel", "rofi", "kitty", "yazi", "helix", "Kvantum"} {
		if err := os.MkdirAll(filepath.Join(configHome, dir), 0o700); err != nil {
			t.Fatalf("MkdirAll(%s) error = %v", dir, err)
		}
	}
	if err := os.WriteFile(filepath.Join(configHome, "kdeglobals"), []byte("[KDE]\n"), 0o600); err != nil {
		t.Fatalf("WriteFile(kdeglobals) error = %v", err)
	}
	theme := planTestTheme()
	theme.Targets = map[string]map[string]string{
		"fuzzel":  {"mode": "generated"},
		"rofi":    {"mode": "generated"},
		"kitty":   {"mode": "generated"},
		"yazi":    {"mode": "generated"},
		"helix":   {"mode": "generated"},
		"kvantum": {"mode": "generated"},
		"kde":     {"mode": "generated"},
	}

	plan, err := BuildApplyPlan(theme, PlanOptions{Mode: "dark", StateHome: "/state", CacheHome: "/cache", ConfigHome: configHome})

	if err != nil {
		t.Fatalf("BuildApplyPlan() error = %v", err)
	}
	assertPlanWriteContains(t, plan, "fuzzel", filepath.Join(configHome, "fuzzel", "orgm-hypr-theme.ini"), []string{
		"# Generated by orgm-hypr theme",
		"background=000000dd",
		"text=eeeeeeff",
		"selection=353438dd",
		"selection-text=eeeeeeff",
		"match=7777ffff",
		"border=7777ffff",
	})
	assertPlanWriteContains(t, plan, "rofi", filepath.Join(configHome, "rofi", "orgm-hypr-theme.rasi"), []string{
		"/* Generated by orgm-hypr theme */",
		`background: rgba(0, 0, 0, 0.86);`,
		`foreground: #eeeeee;`,
		`selected: rgba(53, 52, 56, 0.86);`,
		`border: #7777ff;`,
		`border-radius: 15px;`,
	})
	assertPlanWriteContains(t, plan, "kitty", filepath.Join(configHome, "kitty", "orgm-hypr-theme.conf"), []string{
		"# Generated by orgm-hypr theme",
		"background #000000",
		"foreground #eeeeee",
		"selection_background #353438",
		"cursor #7777ff",
	})
	assertPlanWriteContains(t, plan, "yazi", filepath.Join(configHome, "yazi", "theme.toml"), []string{
		"# Generated by orgm-hypr theme",
		`syntect_theme = "base16-orgm-hypr"`,
		`[manager]`,
		`cwd = { fg = "#7777ff" }`,
	})
	assertPlanWriteContains(t, plan, "helix", filepath.Join(configHome, "helix", "themes", "orgm-hypr.toml"), []string{
		"# Generated by orgm-hypr theme",
		`"ui.background" = { bg = "background" }`,
		`accent = "#7777ff"`,
	})
	assertPlanWriteContains(t, plan, "kvantum", filepath.Join(configHome, "Kvantum", "orgm-hypr", "orgm-hypr.kvconfig"), []string{
		"# Generated by orgm-hypr theme",
		"[General]",
		"base.color=#000000",
		"highlight.color=#7777ff",
	})
	assertPlanWriteContains(t, plan, "kde", filepath.Join(configHome, "kdeglobals.orgm-hypr"), []string{
		"# Generated by orgm-hypr theme",
		"[Colors:Window]",
		"BackgroundNormal=0,0,0",
		"ForegroundNormal=238,238,238",
	})
	for _, want := range []string{
		"fuzzel: include or pass generated theme file manually; existing config was not modified",
		"rofi: import generated theme from config.rasi manually; existing config was not modified",
		"kitty: add include orgm-hypr-theme.conf to kitty.conf manually; existing config was not modified",
		"yazi: generated theme.toml may replace Yazi theme file; review before enabling",
		"helix: set theme = \"orgm-hypr\" in config.toml manually; existing config was not modified",
		"kvantum: select orgm-hypr in Kvantum Manager manually; existing config was not modified",
		"kde: import generated kdeglobals.orgm-hypr manually; existing config was not modified",
	} {
		if !planHasWarning(plan, want) {
			t.Fatalf("warnings = %#v, want %q", plan.Warnings, want)
		}
	}
	for _, unwanted := range []string{
		"kitty: no existing config directory found; generated file is a safe pointer only",
		"kvantum: no existing config directory found; generated file is a safe pointer only",
		"kde: no existing config directory found; generated file is a safe pointer only",
	} {
		if planHasWarning(plan, unwanted) {
			t.Fatalf("warnings = %#v, did not want %q", plan.Warnings, unwanted)
		}
	}
}

func TestBuildApplyPlanWarnsWhenAppConfigDirsAreAbsent(t *testing.T) {
	configHome := t.TempDir()
	theme := planTestTheme()
	theme.Targets = map[string]map[string]string{
		"kitty":   {"mode": "generated"},
		"kvantum": {"mode": "generated"},
		"kde":     {"mode": "generated"},
	}

	plan, err := BuildApplyPlan(theme, PlanOptions{Mode: "light", StateHome: "/state", CacheHome: "/cache", ConfigHome: configHome})

	if err != nil {
		t.Fatalf("BuildApplyPlan() error = %v", err)
	}
	for _, want := range []string{
		"kitty: no existing config directory found; generated file is a safe pointer only",
		"kvantum: no existing config directory found; generated file is a safe pointer only",
		"kde: no existing config directory found; generated file is a safe pointer only",
	} {
		if !planHasWarning(plan, want) {
			t.Fatalf("warnings = %#v, want %q", plan.Warnings, want)
		}
	}
	assertPlanWriteContains(t, plan, "kitty", filepath.Join(configHome, "kitty", "orgm-hypr-theme.conf"), []string{
		"background #ffffff",
		"foreground #111111",
		"cursor #333388",
	})
}

func TestBuildApplyPlanRendersChromiumThemeExportManifest(t *testing.T) {
	theme := planTestTheme()
	theme.Targets = map[string]map[string]string{"chromium": {"mode": "export"}}

	plan, err := BuildApplyPlan(theme, PlanOptions{Mode: "dark", StateHome: "/state", CacheHome: "/cache", ConfigHome: "/config"})

	if err != nil {
		t.Fatalf("BuildApplyPlan() error = %v", err)
	}
	assertPlanWriteContains(t, plan, "chromium", filepath.Join("/state", "orgm-hypr", "theme", "exports", "chromium", "neutral-dark", "manifest.json"), []string{
		`"manifest_version": 3`,
		`"name": "orgm-hypr neutral dark"`,
		`"version": "1.0.0"`,
		`"frame": [`,
		"119,\n        119,\n        255",
		`"toolbar": [`,
		"32,\n        31,\n        35",
		`"tab_text": [`,
		"238,\n        238,\n        238",
		`"ntp_background": [`,
		"0,\n        0,\n        0",
		`"_comment": "Generated by orgm-hypr theme"`,
	})
	if !planHasWarning(plan, "chromium: generated theme export only; load unpacked extension manually and restart Chromium if needed; profile was not modified") {
		t.Fatalf("warnings = %#v, want chromium manual-load no-profile warning", plan.Warnings)
	}
}

func TestBuildApplyPlanIncludesChromiumWallpaperAssetWhenConfigured(t *testing.T) {
	wallpaperPath := filepath.Join(t.TempDir(), "wallpaper.png")
	wallpaperContent := []byte("png-bytes")
	if err := os.WriteFile(wallpaperPath, wallpaperContent, 0o600); err != nil {
		t.Fatalf("WriteFile(wallpaper) error = %v", err)
	}
	theme := planTestTheme()
	theme.Wallpaper = Wallpaper{Path: wallpaperPath}
	theme.Targets = map[string]map[string]string{"chromium": {"mode": "export"}}

	plan, err := BuildApplyPlan(theme, PlanOptions{Mode: "dark", StateHome: "/state", CacheHome: "/cache", ConfigHome: "/config"})

	if err != nil {
		t.Fatalf("BuildApplyPlan() error = %v", err)
	}
	assertPlanWriteContains(t, plan, "chromium", filepath.Join("/state", "orgm-hypr", "theme", "exports", "chromium", "neutral-dark", "manifest.json"), []string{
		`"theme_ntp_background": "wallpaper.png"`,
	})
	assertPlanWriteEquals(t, plan, "chromium", filepath.Join("/state", "orgm-hypr", "theme", "exports", "chromium", "neutral-dark", "wallpaper.png"), wallpaperContent)
}

func TestBuildApplyPlanRendersZenExportNotesWithoutProfileMutation(t *testing.T) {
	theme := planTestTheme()
	theme.Targets = map[string]map[string]string{
		"chromium": {"mode": "export"},
		"zen":      {"mode": "export"},
	}

	plan, err := BuildApplyPlan(theme, PlanOptions{Mode: "light", StateHome: "/state", CacheHome: "/cache", ConfigHome: "/config"})

	if err != nil {
		t.Fatalf("BuildApplyPlan() error = %v", err)
	}
	assertPlanWriteContains(t, plan, "zen", filepath.Join("/state", "orgm-hypr", "theme", "exports", "zen", "neutral-light", "README.md"), []string{
		"# orgm-hypr Zen Browser theme export",
		"Generated by orgm-hypr theme",
		"No Zen profile files were modified.",
		"Copy userChrome.css manually only after backing up your selected profile.",
	})
	assertPlanWriteContains(t, plan, "zen", filepath.Join("/state", "orgm-hypr", "theme", "exports", "zen", "neutral-light", "userChrome.css"), []string{
		"/* Generated by orgm-hypr theme */",
		"--orgm-hypr-background: #ffffff;",
		"--orgm-hypr-foreground: #111111;",
		"--orgm-hypr-accent: #333388;",
	})
	for _, write := range plan.Writes {
		if strings.Contains(write.Path, filepath.Join("/config", "zen")) || strings.Contains(write.Path, filepath.Join("/config", "chromium")) {
			t.Fatalf("browser export wrote profile/config path %q; want state export only", write.Path)
		}
	}
	if !planHasWarning(plan, "zen: generated browser export notes only; copy files manually after reviewing profile path; profile was not modified") {
		t.Fatalf("warnings = %#v, want zen no-profile warning", plan.Warnings)
	}
}

func TestBuildApplyPlanTriangulatesLightModeAndWarnings(t *testing.T) {
	theme := planTestTheme()
	theme.Targets = map[string]map[string]string{
		"gtk":    {"mode": "generated"},
		"qt":     {"mode": "generated"},
		"waybar": {"mode": "generated"},
	}

	plan, err := BuildApplyPlan(theme, PlanOptions{Mode: "light", StateHome: "/state", CacheHome: "/cache", ConfigHome: "/config"})

	if err != nil {
		t.Fatalf("BuildApplyPlan() error = %v", err)
	}
	assertPlanWriteContains(t, plan, "waybar", filepath.Join("/config", "waybar-hypr", "orgm-hypr-theme.css"), []string{
		"@define-color background #ffffff;",
		"@define-color foreground #111111;",
		"@define-color accent #333388;",
	})
	assertPlanWriteContains(t, plan, "gtk", filepath.Join("/config", "gtk-3.0", "orgm-hypr-settings.ini"), []string{
		"gtk-application-prefer-dark-theme=false",
		"gtk-theme-name=Adwaita",
	})
	assertPlanWriteContains(t, plan, "qt", filepath.Join("/config", "qt5ct", "orgm-hypr.conf"), []string{
		"style=Fusion",
	})
	wantWarnings := []string{
		"waybar: import /config/waybar-hypr/orgm-hypr-theme.css from style.css and reload Waybar",
		"gtk: generated settings/CSS require GTK apps to restart or import the CSS manually",
		"qt: generated qt5ct/qt6ct files require selecting orgm-hypr config or restarting Qt apps",
	}
	for _, want := range wantWarnings {
		if !planHasWarning(plan, want) {
			t.Fatalf("warnings = %#v, want %q", plan.Warnings, want)
		}
	}
}

func assertPlanWriteContains(t *testing.T, plan ApplyPlan, target, path string, snippets []string) {
	t.Helper()
	for _, write := range plan.Writes {
		if write.Target == target && write.Path == path {
			content := string(write.Content)
			for _, snippet := range snippets {
				if !strings.Contains(content, snippet) {
					t.Fatalf("write %s content = %q, want snippet %q", path, content, snippet)
				}
			}
			return
		}
	}
	t.Fatalf("missing write target=%s path=%s in %#v", target, path, plan.Writes)
}

func assertPlanWriteEquals(t *testing.T, plan ApplyPlan, target, path string, want []byte) {
	t.Helper()
	for _, write := range plan.Writes {
		if write.Target == target && write.Path == path {
			if string(write.Content) != string(want) {
				t.Fatalf("write %s content = %q, want %q", path, string(write.Content), string(want))
			}
			return
		}
	}
	t.Fatalf("missing write target=%s path=%s in %#v", target, path, plan.Writes)
}

func assertPlanReload(t *testing.T, plan ApplyPlan, target, command string) {
	t.Helper()
	for _, reload := range plan.Reloads {
		if reload.Target == target && reload.Command == command {
			return
		}
	}
	t.Fatalf("missing reload target=%s command=%s in %#v", target, command, plan.Reloads)
}

func planHasWarning(plan ApplyPlan, want string) bool {
	for _, warning := range plan.Warnings {
		if warning == want {
			return true
		}
	}
	return false
}
