-- Optional workspace assignments generated by NWG Displays.

local home = os.getenv("HOME") or ""
if home ~= "" then
  local path = home .. "/.config/hypr/workspaces.lua"
  local file = io.open(path, "r")
  if file then
    file:close()
    dofile(path)
  end
end
