foreground            #e4e2e3
background            #131314
selection_foreground  #1f3241
selection_background  #b5c9db
url_color             #e5bfa2
cursor                #b5c9db
cursor_text_color     #1f3241

color0   #131314
color1   #ffb4ab
color2   #b5c9db
color3   #e5bfa2
color4   #b5c9db
color5   #e5bfa2
color6   #795c44
color7   #e4e2e3

color8   #8d9196
color9   #ffb4ab
color10  #b5c9db
color11  #e5bfa2
color12  #b5c9db
color13  #e5bfa2
color14  #795c44
color15  #e4e2e3

tab_bar_background              #131314
tab_bar_margin_color            #131314
active_tab_foreground           #1f3241
active_tab_background           #b5c9db
inactive_tab_foreground         #c3c7cc
inactive_tab_background         #131314
