conky.config = {
    out_to_wayland = true,
    out_to_x = false,

    own_window_argb_value = 60,

    alignment = 'top_right',
    gap_x = 20,
    gap_y = 710,

    minimum_width = 356,
    maximum_width = 356,
    minimum_height = 0,

    font = 'JetBrainsMono Nerd Font:size=13',

    default_color = 'cad3f5',
    color7 = 'ffffff',
    color8 = 'b7bdf8',

    update_interval = 2,
    double_buffer = true,
    draw_shades = true,
    draw_outline = true,
    draw_borders = false,
    border_width = 0,
    top_name_width = 16,
}

conky.text = [[
${voffset 10}${color8}${font JetBrainsMono Nerd Font:bold:size=12}${alignc}  Top Processes${font}${color}
${voffset 4}${color7}${font JetBrainsMono Nerd Font:size=10}   APP${alignr}CPU%   MEM%  ${font}${color}
${voffset 2}${color7}${font JetBrainsMono Nerd Font:size=12}   ${top name 1}${alignr}${top cpu 1}%   ${top mem 1}%
   ${top name 2}${alignr}${top cpu 2}%   ${top mem 2}%
   ${top name 3}${alignr}${top cpu 3}%   ${top mem 3}%  ${font}${color}
${voffset 8}
]]
