# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=#131315

# Main text color
theme[main_fg]=#e4e2e4

# Title color for boxes
theme[title]=#e4e2e4

# Highlight color for keyboard shortcuts
theme[hi_fg]=#b6c7e7

# Background color of selected item in processes box
theme[selected_bg]=#1f1f21

# Foreground color of selected item in processes box
theme[selected_fg]=#b6c7e7

# Color of inactive/disabled text
theme[inactive_fg]=#8e9098

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]=#e0bbdb

# Background color of the percentage meters
theme[meter_bg]=#8e9098

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]=#e0bbdb

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]=#a8bfff
theme[mem_box]=#c0e5ff
theme[net_box]=#b7baf1
theme[proc_box]=#96beff

# Box divider line and small boxes line color
theme[div_line]=#44474d

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]=#c0e5ff
theme[temp_mid]=#d0f9f4
theme[temp_end]=#a5aeff

# CPU graph colors (Teal -> Sapphire -> Lavender)
theme[cpu_start]=#c6e3ff
theme[cpu_mid]=#a0caff
theme[cpu_end]=#b5cdff

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]=#a8bfff
theme[free_mid]=#b5cdff
theme[free_end]=#96beff

# Mem/Disk cached meter (Sapphire -> Blue -> Lavender)
theme[cached_start]=#a0caff
theme[cached_mid]=#96beff
theme[cached_end]=#b5cdff

# Mem/Disk available meter (Peach -> Maroon -> Red)
theme[available_start]=#e0c2f9
theme[available_mid]=#b7baf1
theme[available_end]=#a5aeff

# Mem/Disk used meter (Green -> Teal -> Sky)
theme[used_start]=#c0e5ff
theme[used_mid]=#c6e3ff
theme[used_end]=#c1deff

# Download graph colors (Peach -> Maroon -> Red)
theme[download_start]=#e0c2f9
theme[download_mid]=#b7baf1
theme[download_end]=#a5aeff

# Upload graph colors (Green -> Teal -> Sky)
theme[upload_start]=#c0e5ff
theme[upload_mid]=#c6e3ff
theme[upload_end]=#c1deff

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Lavender -> Mauve)
theme[process_start]=#a0caff
theme[process_mid]=#b5cdff
theme[process_end]=#a8bfff
