general {
    hide_cursor = true
}

background {
    monitor =
    path = $XDG_RUNTIME_DIR/hypr-current-wallpaper
    blur_passes = 3
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 320, 56
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.18
    dots_center = true
    outer_color = rgba(8aadf4ee)
    inner_color = rgba(24273add)
    font_color = rgba(cad3f5ff)
    fade_on_empty = false
    placeholder_text = <i>Password...</i>
    position = 0, -40
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"%I:%M %p"
    color = rgba(cad3f5ff)
    font_size = 54
    font_family = JetBrainsMono Nerd Font
    position = 0, 80
    halign = center
    valign = center
}
