profile=gpu-hq
gpu-api=vulkan
vo=gpu-next
hwdec=auto-safe
save-position-on-quit=yes
keep-open=yes
osc=yes
osd-bar=yes
sub-auto=fuzzy
slang=spa,es,en
alang=spa,es,en
screenshot-directory=~/Pictures/Screenshots
