# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make hardware-specific
# reusable changes in modules imported by the flake.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  services.xserver.xkb = {
    layout = "us,latam";
    variant = "altgr-intl,";
    options = "grp:ctrl_space_toggle";
  };

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/home" = {
    device = "/dev/nvme0n1p5";
    fsType = "ext4";
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/8417da22-d554-4f06-ab91-f384ddfb3df4";
    fsType = "ext4";
    neededForBoot = true;
  };

  # /nix must survive reboots (NixOS only needs /boot + /nix to boot — see
  # wiki.nixos.org/wiki/Impermanence). Bind-mounted from the same persisted
  # partition's existing /nix subdirectory — no data migration needed, the
  # store is already there since this partition used to be root.
  fileSystems."/nix" = {
    device = "/persist/nix";
    fsType = "none";
    options = [ "bind" ];
    neededForBoot = true;
  };

  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = [
      "size=8G"
      "mode=755"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/6AA0-C007";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

}
