# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];
  # Habilitar drivers NVIDIA
  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.graphics = {
  	enable = true;
  	enable32Bit = true;
	};

  services.xserver.xkb = {
    layout = "us,latam";
    variant = "altgr-intl,";
    options = "grp:ctrl_space_toggle";
  };

  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    wireplumber.enable = true;
  };

  hardware.nvidia-container-toolkit.enable = true;

  hardware.nvidia = {
    modesetting.enable = true;
  
    # ESTO ES CLAVE - habilitar power management
    powerManagement.enable = true;
  
    # Preservar memoria de video durante suspend
    powerManagement.finegrained = false;
  
    # Usar drivers propietarios cerrados (más estables para suspend)
    open = false;
  
    nvidiaSettings = true;
    package = config.boot.kernelPackages.nvidiaPackages.stable;
  };

  # Agregar parámetro del kernel para preservar asignación de memoria
  boot.kernelParams = [ 
  "nvidia.NVreg_PreserveVideoMemoryAllocations=1"
  ];

  # Habilitar los servicios de systemd para suspend/resume
  boot.extraModprobeConfig = ''
  options nvidia NVreg_PreserveVideoMemoryAllocations=1
  '';




  # Asegurar que el módulo se carga al boot
  boot.kernelModules = [ "nvidia" "nvidia_drm" "nvidia_modeset" ];

  # hardware.nvidia.enabled = true;
  # hardware.nvidia.open = true;
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/home" = 
    { device = "/dev/nvme0n1p5";
      fsType = "ext4";
    };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8417da22-d554-4f06-ab91-f384ddfb3df4";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6AA0-C007";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

}
