# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make hardware-specific
# reusable changes in modules imported by the flake.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/e9cda353-c924-4aed-b348-5de16c35e40a";
    fsType = "ext4";
    neededForBoot = true;
  };

  # /nix must survive reboots (NixOS only needs /boot + /nix to boot — see
  # wiki.nixos.org/wiki/Impermanence). Bind-mounted from the same persisted
  # partition's existing /nix subdirectory — no data migration needed, the
  # store is already there since this partition used to be root.
  fileSystems."/nix" = {
    device = "/persist/nix";
    fsType = "none";
    options = [ "bind" ];
    neededForBoot = true;
  };

  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = [
      "size=8G"
      "mode=755"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/67C9-6B78";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/525a43ad-c883-44dc-aecc-d9473549c03f";
    fsType = "ext4";
  };

  swapDevices = [ { device = "/dev/disk/by-uuid/c6da324c-0bf7-4a44-b563-8a2e1a9a775c"; } ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
